### ISSUE TITLE
Buffering

### ISSUE THREAD

**Issue by PartapSBimrah** [seemantshekhar43/Befikre#1]
It takes a lot of time to create account and the loader shows on the screen and not move forward.

**Comment by seemantshekhar43** [comment]
It's working for me. Can you share the debug details of that instance?

**Comment by PartapSBimrah** [comment]
When I create an account using the RealTime Database in locked mode. It doesn't work. But if we work in test mode. It's working fine.

**Comment by seemantshekhar43** [comment]
share the debug details of that instance

**Comment by PartapSBimrah** [comment]
sure I will 


```
E/WindowManager: android.view.WindowLeaked: Activity com.royalbimrah.befikre.SignUpActivity has leaked window DecorView@a472509[SignUpActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:769)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:429)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
        at android.app.Dialog.show(Dialog.java:473)
        at com.royalbimrah.befikre.SignUpActivity$2.onClick(SignUpActivity.java:104)
        at android.view.View.performClick(View.java:7870)
        at android.widget.TextView.performClick(TextView.java:14970)
        at android.view.View.performClickInternal(View.java:7839)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29363)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
D/ViewRootImpl@7d29340[SignUpActivity]: dispatchDetachedFromWindow
D/InputTransport: Input channel destroyed: '61a44c2', fd=87
W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid byte order: ffff8950
        at android.media.ExifInterface.readByteOrder(ExifInterface.java:3153)
        at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2446)
        at android.media.ExifInterface.getMimeType(ExifInterface.java:2324)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1758)
        at android.media.ExifInterface.<init>(ExifInterface.java:1452)
        at com.bumptech.glide.load.resource.bitmap.ExifInterfaceImageHeaderParser.getOrientation(ExifInterfaceImageHeaderParser.java:40)
        at com.bumptech.glide.load.ImageHeaderParserUtils.getOrientation(ImageHeaderParserUtils.java:91)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:236)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:206)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:162)
        at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:33)
        at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:16)
        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:515)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:480)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:466)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:387)
        at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
        at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
        at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
        at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3c158af[EditProfile]
D/InputMethodManager: getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.royalbimrah.befikre ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel destroyed: 'ClientS', fd=92
D/ViewRootImpl@c22615e[EditProfile]: stopped(true) old=false
E/ViewRootImpl@c22615e[EditProfile]: Surface is not valid.
D/ViewRootImpl@c22615e[EditProfile]: MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3c158af[EditProfile]
    getNavigationBarColor() -855310
E/ViewRootImpl@c22615e[EditProfile]: Surface is not valid.
```

**Comment by PartapSBimrah** [comment]
Add the chat system in this app.

**Comment by PartapSBimrah** [comment]
![shell php](https://user-images.githubusercontent.com/39325207/95086080-b241fa80-073d-11eb-8425-b2895d366189.jpg)
